name: Build Mobile Offline APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Create Web Directory
        run: |
          mkdir build
          cp index.html build/

      - name: Convert to Android APK
        uses: darkshredder/website-to-apk-action@v2.2
        with:
          build-folder-path: "build"
          app-name: "UAQ Security"
          output-folder-path: "output"

      - name: Upload APK File Artifact
        uses: actions/upload-artifact@v3
        with:
          name: UAQ-Security-App
          path: output/
